apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBb0f7YfROBnmMboEabEftcFeR7lLBK7JPFglHPLga9Ux7/gn2OclpvHGMKoy5+6b6XVMDCQKAIl7b58MEITFGXeQt69LWYCe4OaQ/drCAvdv/tJdYKQuEFJPfGe7AFEuVb+Rrf0GUTAUD2cHiSUvRkcbL8gG1FNiCHW1FuBjCl+b4YjRmqd/AOW/HhBYGYQ9Zla03cyEgHZQgXH8ZiKYansSrl6g5K3uRT4NW2hcqc5lKAIKrjY0bDK1AhNzaaUOl88OF8xSwwaw0NSSnDgtMbTC8ujfuVIs/9LsfHxtvXK1eYRA3j7BCHVD5ScmQAGtgMgdfqOO6raNXlhpfLuCU2ct0fyWjwhxJ2qCW5j1N64HENRmgOPxw3ij+53rnQq4fTpgKSVUwQ16kvhuWMq8C2QkM0bZVwn0tld7Jw/jKF0xxQ+xJwp80Govyzqv8SNc5tKbCgD9jXduXnYletcp2obQA+nhGMHy+XWAW/oIcS+v3Di0amk3YKTUcKcKoHpHgIxPCwyUZjG5i5g6ECqCTx81uPCwMjYb2N1+rdIhCitGepEm1/7jzLkeDkngly5hsMfaPbWKLbGYBZB6W/hw14jdAqIOBJLr5ErKehjqITfugYMZBLayY4QnNr7RJAM6JYytJN6OlIgt8+05V2rmw7sxzkRTJeQb9Af0MfUFHsE+7z9SrloaQvsof74YXrF7c3+C6cPx72HTyS1b9dey2bMmcfd+3N+Y1qS9HtUwCi00kn+I6BEWWRZtlMCofic9x3OuE3STPcuAm7BaqOix/Y7ksdn0QL0sAUzrTPPLC7AuN1zSobS+J2wxob3d8bVCrT3otLGeAVRtydcVHIvO5MFJYKBDw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

