apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAjl9OCKqJV+5yVZ2jtd38oe9Lsn1lB9CWF39RQ2frU9LGHsq7EsLNtJNN/69O0EaVw8viFinIk+v5tjrt78us56IsKWuroG6djJ8xEZiIzDGlgTH3osg/0HsEfBVGdz45Hq88i7Akhxp5jsvpf5YnBrylpFR+fmaZSc1hZ2xnQIcvWRLD5JOEpMvhtPfgOQJnNQcFOliVrmEzCyyHJAiCKf3UzUjzTqXtqe3cLyDcYYiNf9kdfjaDpHXQNnLv9eIT5Dw4tntTbQBDJOt5S2KnV1AzLJoUWK6uM70IlrCBaJzkLUf+f3Gb76LS9EhO/43+77abalKlB+qVGchwidZPykOAfnSCvBXl5ubNWWgehptUAZLOMNN4qZIRHoLFaK4Hxy3f9iPrUy9B47NoY/C8dzf9cfKry5RjLuyzA9ANL97a+FN8ryNV/KZDmnuLpnfHztYfQIMZ4bs3xYrNlg0TRr52E/E3M72NmTyGo92YmrxqKe1gydrYexqMXaeu/T9oSMm9jEgr89E/SukAkEk5qA75NjMPT6xaD90C4ufOa59lmdvS6pnNAHp4FQwvq0HdCVpvOeu9QRpGb0e5OPayNcMumScHdXOJzhQJQ672gDbY652jm210xopbiehTVLs2mwxCBvHO25RZ6y3SteMGXBxtzysvlv8+cvkwyVX1wbRP8aVEJZwTdKHKgXpoJUYAdWYiUrKdYK/ADA1wrnrRv3Y65QA+LxNY9OQ0ooWkj81TXsgdT36KrFIFpQNL5XuVVef5hN1sqysHB+oaDMxRGDUfkFHR2AgzbDu9V6BMtjrPN0AiVn1icH76F7f5fB9etklAt4LHaVuvaKWSGsSACTCNp9kQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

